CREATE TABLE USERS (USERNAME VARCHAR(50) NOT NULL, PASSWORD VARCHAR(50) NOT NULL, FULL_NAME VARCHAR(50), PHONE_NUMBER VARCHAR(50), ADDRESS VARCHAR(50), PRIMARY KEY (USERNAME));

CREATE TABLE USER_ROLES (user_role_id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), USERNAME VARCHAR(50) NOT NULL, "ROLE" VARCHAR(50) NOT NULL, PRIMARY KEY (USER_ROLE_ID),FOREIGN KEY (username) REFERENCES users(username));

INSERT INTO NBUSER.USERS (USERNAME, PASSWORD, FULL_NAME, PHONE_NUMBER, ADDRESS) 
    VALUES ('keith', '{noop}keithpw', NULL, NULL, NULL);
INSERT INTO NBUSER.USERS (USERNAME, PASSWORD, FULL_NAME, PHONE_NUMBER, ADDRESS) 
    VALUES ('john', '{noop}johnpw', NULL, NULL, NULL);
INSERT INTO NBUSER.USERS (USERNAME, PASSWORD, FULL_NAME, PHONE_NUMBER, ADDRESS) 
    VALUES ('mary', '{noop}marypw', NULL, NULL, NULL);

INSERT INTO NBUSER.USER_ROLES (USERNAME, "ROLE") 
    VALUES ('keith', 'ROLE_USER');
INSERT INTO NBUSER.USER_ROLES (USERNAME, "ROLE") 
    VALUES ('keith', 'ROLE_ADMIN');
INSERT INTO NBUSER.USER_ROLES (USERNAME, "ROLE") 
    VALUES ('john', 'ROLE_ADMIN');
INSERT INTO NBUSER.USER_ROLES (USERNAME, "ROLE") 
    VALUES ('mary', 'ROLE_USER');
