CREATE TABLE USERS
(
	USERNAME VARCHAR(50) not null primary key,
	PASSWORD VARCHAR(50) not null,
	FULL_NAME VARCHAR(50),
	PHONE_NUMBER VARCHAR(50),
	ADDRESS VARCHAR(50)
);
CREATE TABLE user_roles (
 user_role_id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
 username VARCHAR(50) NOT NULL,
 role VARCHAR(50) NOT NULL,
 PRIMARY KEY (user_role_id),
 FOREIGN KEY (username) REFERENCES users(username)
);

INSERT INTO users VALUES ('keith', '{noop}keithpw','keith','12345678','address');
INSERT INTO user_roles(username, role) VALUES ('keith', 'ROLE_USER');
INSERT INTO user_roles(username, role) VALUES ('keith', 'ROLE_ADMIN');
INSERT INTO NBUSER.USER_ROLES (USERNAME, "ROLE") 
	VALUES ('danny', 'ROLE_USER');
INSERT INTO NBUSER.USER_ROLES (USERNAME, "ROLE") 
	VALUES ('peter', 'ROLE_USER');
