CREATE TABLE poll (
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    question VARCHAR(200) DEFAULT NULL,
    choice1 VARCHAR(200) DEFAULT NULL,
    choice2 VARCHAR(200) DEFAULT NULL,
    choice3 VARCHAR(200) DEFAULT NULL,
    choice4 VARCHAR(200) DEFAULT NULL,
    PRIMARY KEY(id)
);
CREATE TABLE guestbook (
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    poll_id INTEGER DEFAULT NULL,
    name VARCHAR(50),
    message VARCHAR(200),
    date TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (poll_id) REFERENCES poll(id)
);

CREATE TABLE answer(
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    poll_id INTEGER DEFAULT NULL,
    name VARCHAR(200) DEFAULT NULL,
    ans INTEGER DEFAULT NULL,
    FOREIGN KEY (poll_id) REFERENCES poll(id)
);    

